**Question 1:What is TensorFlow? Explain its main features and why it is widely used for developing deep learning applications**

**Answer:** TensorFlow is an open-source, end-to-end machine learning and deep learning platform developed by the Google Brain team. It provides a comprehensive ecosystem of tools, libraries, and community resources that allow developers and researchers to build, train, and deploy machine learning-powered applications.

At its core, TensorFlow operates on multidimensional arrays known as tensors and performs computations using dataflow graphs, where nodes represent mathematical operations and edges represent the tensors flowing between them.

**Main Features of TensorFlow**

High-Level API (tf.keras): Integrates Keras as its default high-level interface, enabling fast prototyping, model building, and training with user-friendly constructs (Sequential, Functional, and subclassing APIs).

Eager Execution: Runs operations imperatively by default, returning concrete values immediately (like standard Python code) rather than constructing static computational graphs first. This simplifies debugging and inspection.

Graph Optimization (tf.function): Uses the AutoGraph engine to compile standard Python functions into high-performance, optimized static computation graphs for production-level throughput.

Automatic Differentiation (tf.GradientTape): Automatically computes gradients with respect to specified variables, simplifying custom loss calculations, layer design, and backpropagation.

Why TensorFlow Is Widely Used for Deep Learning

Hardware Acceleration & Scalability: Native support for CPU, GPU (CUDA), and Google TPU (Tensor Processing Unit) acceleration with minimal code modifications via tf.distribute.Strategy for distributed multi-GPU training.

End-to-End Production Readiness: Unlike research-only frameworks, TensorFlow offers a seamless path from research notebooks to scalable production pipelines through the TFX (TensorFlow Extended) ecosystem.

Cross-Language & Ecosystem Support: While primarily developed and used in Python, it provides APIs and bindings for C++, Java, JavaScript, and Swift.

Enterprise Adoption & Pre-trained Models: Backed by Google and heavily adopted across major enterprise environments, supported by extensive model hubs (like TensorFlow Hub / Kaggle Models) offering pre-trained weights for transfer learning.

**Question 2: What is PyTorch? Explain its important features and mention three real-world applications of PyTorch?**

**Answer:** PyTorch is an open-source deep learning framework developed primarily by Meta AI (formerly Facebook AI Research). Based on the Torch library, it provides a flexible, Python-first platform for tensor computation with strong GPU acceleration and automatic differentiation for building deep neural networks.

Important Features of PyTorch

Dynamic Computational Graphs (Define-by-Run): Builds graphs dynamically at runtime as operations are executed. This allows standard Python control structures (if, for, while) to alter the graph on the fly, making dynamic architectures (like variable-length RNNs or tree-structured models) intuitive to build and debug.

Native Pythonic Design: Behaves seamlessly as standard Python code. It integrates directly with the NumPy ecosystem (torch.from_numpy() and .numpy()) and allows straightforward debugging using standard tools like pdb or IDE breakpoints.

Automatic Differentiation (torch.autograd): Automatically computes gradients during the backward pass for all tensor operations where requires_grad=True, handling complex backpropagation chains without manual gradient derivation.

TorchScript (JIT Compilation): Allows Python-based PyTorch models to be converted into static, serializable C++ graphs using torch.jit.trace or torch.jit.script for high-throughput, low-latency deployment in environments without a Python runtime.

torch.distributed & Ecosystem: Native support for distributed multi-GPU and multi-node training using Distributed Data Parallel (DDP), supported by domain-specific libraries like torchvision (Computer Vision), torchaudio (Audio), and torchtext (NLP).

---

**Question 3: What is a Convolutional Neural Network? Explain why CNNs are more suitable than fully connected neural networks for image processing.**

**Answer:** A Convolutional Neural Network (CNN) is a specialized class of deep neural networks designed primarily to process grid-structured topology, such as 2D images or 1D audio sequences.

Instead of treating an image as a flat vector of independent values, a CNN applies learnable kernel filters that slide across the input spatial dimensions to extract local patterns (like edges, textures, and shapes) into feature maps.

Why CNNs Outperform Fully Connected (FC) Networks for Image Processing

1. Spatial Locality and Preservation of StructureFully Connected Networks: Require 2D/3D images to be flattened into a 1D vector (e.g., a $28 \times 28 \times 1$ image becomes a 784-length vector). This destroys the spatial adjacency between neighboring pixels.CNNs: Process images in their native 2D/3D matrix format, capturing spatial correlations because neighboring pixels are evaluated together within the kernel's receptive field.


2. Parameter Sharing & Memory EfficiencyFully Connected Networks: Every input pixel connects to every neuron. For a modest $200 \times 200 \times 3$ RGB image (120,000 inputs) connected to a hidden layer of 1,000 neurons, this requires:$$120{,}000 \times 1{,}000 = 120\text{ million weights}$$This causes explosive memory usage and severe overfitting.CNNs: Share filter weights across the entire image. A $3 \times 3$ filter on 3 channels has only $3 \times 3 \times 3 = 27$ weights (plus 1 bias), regardless of the input image resolution.


3. Translation InvarianceFully Connected Networks: If a cat appears in the top-left corner during training, an FC network will fail to detect that same cat if it appears in the bottom-right corner during inference without separate training data for that exact position.CNNs: Because the same convolutional kernel slides across the entire image, a feature detected in one region (e.g., an ear or eye) is recognized equally anywhere else in the frame.

---

**Question 4:Compare LeNet-5, AlexNet, and VGGNet. Mention the main purpose, important features, advantages, and limitations of each architecture**

**Answer:**

**1. LeNet-5 (1998)**

**Main Purpose:** Automate handwritten digit and character recognition on bank checks and postal zip codes (MNIST dataset).

**Important Features:**

Uses a 7-layer architecture (2 Convolutional, 2 Average Pooling/Subsampling, and  3 Fully Connected layers).

Designed for $32 \times 32 \times 1$ grayscale images.

Relies on hyperbolic tangent ($\tanh$) and Sigmoid activation functions.

Uses $5 \times 5$ filter kernels and average pooling for downsampling.

**Advantages:**

Very lightweight footprint with only $\sim 60{,}000$ trainable parameters.

Extremely low compute requirement, running smoothly on standard CPUs.

Established the standard sequence ([Conv -> Subsample -> Conv -> Subsample -> Dense]) for future CNN designs.

**Limitations:**

Unable to scale to high-resolution, complex multi-channel RGB datasets like ImageNet.
Suffers from the vanishing gradient problem due to saturating Sigmoid and Tanh activations.
Average pooling blurs sharp edges and washes out important localized spatial features.

**2. AlexNet (2012)**

**Main Purpose:** High-accuracy classification on large-scale, high-resolution color images across 1,000 object categories (ImageNet/ILSVRC 2012).

**Important Features:**

An 8-layer deep architecture consisting of 5 Convolutional layers and 3 Fully Connected layers.

Designed for $224 \times 224 \times 3$ RGB inputs.

Replaced saturating activations with ReLU non-linearities.

Introduced Dropout (0.5) in the dense layers to regularize the network, paired with data augmentation.

Utilized overlapping Max Pooling ($3 \times 3$ with stride 2).

**Advantages:**

Successfully demonstrated that deep networks can scale to complex, diverse real-world images.

ReLU accelerated training convergence by up to 6x compared to Tanh/Sigmoid.

Overlapping max pooling significantly reduced top-1 and top-5 error rates while resisting overfitting.

**Limitations:**

High parameter count ($\sim 60\text{ million}$), heavily concentrated in the large dense layers.

Computationally inefficient early layers using large $11 \times 11$ and $5 \times 5$ filter kernels.

Relied on Local Response Normalization (LRN), which added memory and compute overhead with minimal practical benefit.

**3. VGGNet / VGG-16 (2014)**


**Main Purpose:** Systematically evaluate the direct impact of network depth on classification accuracy in large-scale visual recognition challenges.

**Important Features:**

Deep architectures of 16 to 19 weight layers (VGG-16 uses 13 Convolutional and 3 Fully Connected layers).

Standardized entirely on homogeneous stacks of tiny $3 \times 3$ convolutional filters (stride 1, pad 1) combined with $2 \times 2$ Max Pooling.

Stacking two $3 \times 3$ convolutions yields the effective receptive field of a $5 \times 5$ kernel, while stacking three mimics a $7 \times 7$ kernel with fewer parameters and more non-linear activation steps.

**Advantages:**

Uniform, modular architecture that is straightforward to implement, fine-tune, and understand.

Produces high-quality, generalizable feature representations, making it an effective backbone for transfer learning (e.g., style transfer, object detection).

Proved that deep architectures with smaller kernels outperform shallow architectures with larger kernels.

**Limitations:**

Massive parameter footprint ($\sim 138\text{ million}$ for VGG-16), requiring substantial disk storage (>500MB) for model weights.

Extremely slow training and high GPU memory consumption during forward and backward passes.

Inefficient top layers where over 100 million parameters reside solely inside the first two fully connected layers (Linear(25088, 4096)).

---


**Question 5: What is transfer learning? Explain feature extraction and fine-tuning. Also briefly explain the main idea behind ResNet, Inception, MobileNet, and EfficientNet**

**Answer:** Transfer learning is a machine learning technique where a model trained on a large benchmark dataset (such as ImageNet with 1.4 million images) is repurposed as the starting point for a different, often smaller, target task. Instead of training deep neural networks from scratch with random weight initialization, transfer learning leverages learned low-level representations (edges, curves, textures) and high-level abstract shapes to save computational resources and accelerate convergence.

**Feature Extraction (Frozen Backbone):**

You take a pre-trained network, remove its original classification head (the final dense layers), and replace it with a new task-specific classifier.

The entire convolutional base (the "backbone") is frozen—meaning its weights are kept static and will not update during backpropagation.

Only the newly added classification layers compute gradients and update weights.

Best used when: The target dataset is small and visually similar to the original dataset.

**Fine-Tuning (Selective Unfreezing):**

You replace the final classification head, but you also unfreeze some or all of the top convolutional layers in the base model.

The entire network (or the unfrozen sub-layers) is trained jointly using a very small learning rate (e.g., $10^{-5}$ to $10^{-4}$) to prevent "catastrophic forgetting" of the generic pre-trained weights while adapting high-level features to the new task domain.

Best used when: The target dataset is moderately large or differs significantly in domain from the original training data.


**Main Ideas Behind Key CNN Architectures**

ResNet (Residual Networks):  Introduces skip (residual) connections that bypass one or more layers, formulating the layer mapping as $\mathcal{F}(x) + x$ instead of direct fitting $\mathcal{H}(x)$.

Inception (GoogLeNet): Multi-scale processing through the Inception module, which applies multiple filter sizes ($1 \times 1$, $3 \times 3$, $5 \times 5$) and max pooling in parallel at the same layer depth, concatenating their outputs.

MobileNet: Replaces expensive standard 2D convolutions with Depthwise Separable Convolutions, which split the operation into:

Depthwise Convolution: Applies a single spatial filter per input channel.

Pointwise Convolution: Uses a $1 \times 1$ convolution to combine the filtered channel outputs linearly.

EfficientNet: Introduces Compound Scaling, a systematic method to scale up networks balancing all three dimensions: depth (number of layers), width (number of channels), and resolution (input image size) using a fixed compound coefficient $\phi$.

In [1]:
'''
Question 6: Write a TensorFlow program to:
● Create two 2 × 2 tensors.
● Perform addition.
● Perform element-wise multiplication.
● Perform matrix multiplication.
● Display the shape, rank, and data type of one tensor

'''

import tensorflow as tf

# 1. Create two 2x2 tensors
tensor_a = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)

tensor_b = tf.constant([[5.0, 6.0], [7.0, 8.0]], dtype=tf.float32)

print("Tensor A:\n", tensor_a.numpy())
print("\nTensor B:\n", tensor_b.numpy())

# 2. Perform addition
add_result = tf.add(tensor_a, tensor_b)  # or: tensor_a + tensor_b
print("\nAddition (A + B):\n", add_result.numpy())

# 3. Performing element-wise multiplication
elem_mult_result = tf.multiply(
    tensor_a, tensor_b
)  # or: tensor_a * tensor_b
print("\nElement-wise Multiplication (A * B):\n", elem_mult_result.numpy())

# 4. Performing matrix multiplication
matmul_result = tf.matmul(tensor_a, tensor_b)  # or: tensor_a @ tensor_b
print("\nMatrix Multiplication (A @ B):\n", matmul_result.numpy())

# 5. Display shape, rank, and data type of tensor_a
print("\n--- Tensor A Properties ---")
print("Shape:    ", tensor_a.shape)
print("Rank (ndim):", tf.rank(tensor_a).numpy())
print("Data Type:", tensor_a.dtype)

Tensor A:
 [[1. 2.]
 [3. 4.]]

Tensor B:
 [[5. 6.]
 [7. 8.]]

Addition (A + B):
 [[ 6.  8.]
 [10. 12.]]

Element-wise Multiplication (A * B):
 [[ 5. 12.]
 [21. 32.]]

Matrix Multiplication (A @ B):
 [[19. 22.]
 [43. 50.]]

--- Tensor A Properties ---
Shape:     (2, 2)
Rank (ndim): 2
Data Type: <dtype: 'float32'>


In [2]:
'''
Question 7: Using tf.GradientTape(), calculate the gradient of the following function at x
= 3: [y = x^2 + 2x + 1]
Write the TensorFlow code and explain the result.
'''

import tensorflow as tf

# 1. Define the input variable at x = 3.0
x = tf.Variable(3.0)

# 2. Record operations on the variable within GradientTape context
with tf.GradientTape() as tape:
    y = x**2 + 2 * x + 1

# 3. Compute the derivative of y with respect to x: dy/dx
dy_dx = tape.gradient(y, x)

print(f"Value of y at x = 3: {y.numpy()}")
print(f"Gradient (dy/dx) at x = 3: {dy_dx.numpy()}")

Value of y at x = 3: 16.0
Gradient (dy/dx) at x = 3: 8.0


In [3]:
'''
Question 8: Build a simple TensorFlow and Keras neural network for classifying MNIST
handwritten digits.
The model must contain:
● A Flatten layer
● One hidden Dense layer
● A Dropout layer
● A Softmax output layer
Train and evaluate the model
'''
import tensorflow as tf

# 1. Load and preprocess the MNIST dataset
mnist = tf.keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Normalization pixel values from [0, 255] to [0.0, 1.0]
X_train = X_train / 255.0
X_test = X_test / 255.0

# 2. Building the model architecture
model = tf.keras.Sequential(
    [
        # Layer 1: Flatten 28x28 images into a 784-element 1D vector
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        # Layer 2: Hidden Dense layer with ReLU activation
        tf.keras.layers.Dense(128, activation="relu"),
        # Layer 3: Dropout layer to prevent overfitting
        tf.keras.layers.Dropout(0.2),
        # Layer 4: Output Dense layer with Softmax activation for 10 digit classes (0-9)
        tf.keras.layers.Dense(10, activation="softmax"),
    ]
)

# 3. Compiling the model
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

# 4. Training the model
history = model.fit(
    X_train,
    y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.1,
    verbose=1,
)

# 5. Evaluating the model on unseen test data
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)

print(f"\nTest Loss:     {test_loss:.4f}")
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


/usr/local/lib/python3.13/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
844/844 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8978 - loss: 0.3538 - val_accuracy: 0.9620 - val_loss: 0.1434
Epoch 2/5
844/844 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9498 - loss: 0.1720 - val_accuracy: 0.9700 - val_loss: 0.1016
Epoch 3/5
844/844 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9625 - loss: 0.1269 - val_accuracy: 0.9745 - val_loss: 0.0871
Epoch 4/5
844/844 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9689 - loss: 0.1035 - val_accuracy: 0.9775 - val_loss: 0.0779
Epoch 5/5
844/844 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9740 - loss: 0.0877 - val_accuracy: 0.9783 - val_loss: 0.0742

Test Loss:     0.0775
Test Accuracy: 97.56%


**Architecture Breakdown**

Flatten(input_shape=(28, 28)): Transforms each $28 \times 28$ 2D matrix into a 784-element 1D vector without altering data values.

Dense(128, activation='relu'): Fully connected hidden layer with 128 neurons utilizing the Rectified Linear Unit activation function ($f(x) = \max(0, x)$) to learn non-linear representations.

Dropout(0.2): Randomly deactivates 20% of the hidden neurons during each training step, reducing co-adaptation and regularizing the model against overfitting.

Dense(10, activation='softmax'): Generates a probability distribution over the 10 target classes ($0$ through $9$) where the sum of outputs equals $1.0$.

sparse_categorical_crossentropy: Selected because the target labels ($y$) are provided as integers ($0$ to $9$) rather than one-hot encoded vectors.

In [4]:
'''
Question 9: Write a PyTorch program to:
Write a PyTorch program to:
● Create two tensors.
● Perform tensor addition.
● Perform matrix multiplication.
● Reshape a tensor.
● Calculate the gradient of the following function at x = 4:
[y = x^2 + 3x]
'''

import torch

# 1. Create two 2x2 tensors
A = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

B = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

print("Tensor A:\n", A)
print("\nTensor B:\n", B)

# 2. Perform tensor addition
add_result = torch.add(A, B)  # or: A + B
print("\nAddition (A + B):\n", add_result)

# 3. Perform matrix multiplication
matmul_result = torch.matmul(A, B)  # or: A @ B
print("\nMatrix Multiplication (A @ B):\n", matmul_result)

# 4. Reshape a tensor (from 2x2 to 1x4 and 4x1)
reshaped_1x4 = A.view(1, 4)  # or: A.reshape(1, 4)
reshaped_4x1 = A.view(4, 1)  # or: A.reshape(4, 1)
print("\nReshaped Tensor A to (1, 4):\n", reshaped_1x4)
print("\nReshaped Tensor A to (4, 1):\n", reshaped_4x1)

# 5. Calculate gradient of y = x^2 + 3x at x = 4
x = torch.tensor(4.0, requires_grad=True)

# Define the function
y = x**2 + 3 * x

# Compute backward pass (autograd)
y.backward()

print("\n--- Gradient Calculation ---")
print(f"Value of y at x = 4: {y.item()}")
print(f"Gradient (dy/dx) at x = 4: {x.grad.item()}")

Tensor A:
 tensor([[1., 2.],
        [3., 4.]])

Tensor B:
 tensor([[5., 6.],
        [7., 8.]])

Addition (A + B):
 tensor([[ 6.,  8.],
        [10., 12.]])

Matrix Multiplication (A @ B):
 tensor([[19., 22.],
        [43., 50.]])

Reshaped Tensor A to (1, 4):
 tensor([[1., 2., 3., 4.]])

Reshaped Tensor A to (4, 1):
 tensor([[1.],
        [2.],
        [3.],
        [4.]])

--- Gradient Calculation ---
Value of y at x = 4: 28.0
Gradient (dy/dx) at x = 4: 11.0


In [5]:
'''
Question 10: A company has a small image dataset containing four classes. Build a
transfer-learning model using a pre-trained MobileNetV2 model.
The program should:
1. Load MobileNetV2 without its original classification layer.
2. Freeze the pre-trained layers.
3. Add a new classification head.
4. Compile the model.
5. Display the model summary
'''
import tensorflow as tf
from tensorflow.keras import layers, models

# Define configuration parameters
IMG_SHAPE = (224, 224, 3)
NUM_CLASSES = 4

# 1. Load MobileNetV2 without the original top classification layer
base_model = tf.keras.applications.MobileNetV2(
    input_shape=IMG_SHAPE,
    include_top=False,  # Excludes the 1000-class ImageNet classification head
    weights="imagenet",  # Loads pre-trained ImageNet weights
)

# 2. Freeze the pre-trained convolutional base
base_model.trainable = False

# 3. Add a new custom classification head using the Functional API
inputs = tf.keras.Input(shape=IMG_SHAPE)

# Apply MobileNetV2-specific pixel preprocessing (scales [0, 255] to [-1, 1])
x = tf.keras.applications.mobilenet_v2.preprocess_input(inputs)

# Pass inputs through the frozen base model (set training=False for BatchNorm stability)
x = base_model(x, training=False)

# Spatial pooling and custom dense layers
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(128, activation="relu")(x)
x = layers.Dropout(0.2)(x)
outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)

# Construct the full transfer learning model
model = models.Model(inputs=inputs, outputs=outputs)

# 4. Compile the model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",  # Or 'categorical_crossentropy' if one-hot encoded
    metrics=["accuracy"],
)

# 5. Display the model summary
model.summary()

9406464/9406464 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)      │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ true_divide (TrueDivide)        │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ subtract (Subtract)             │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ mobilenetv2_1.00_224            │ (None, 7, 7, 1280)     │     2,257,984 │
│ (Functional)                    │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 1280)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │       163,968 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 4)              │           516 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,422,468 (9.24 MB)

 Trainable params: 164,484 (642.52 KB)

 Non-trainable params: 2,257,984 (8.61 MB)